# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee4cef998797223b58315ef6afb2ca5b5cab982e0e8d17424af7ce34e30cdcdc0fb991e82ca7337ee89238660cb1ef5af8e161610eed9d33a21c6f17ff0a5934

test:
  secret_key_base: 7d102453eca56d81fe87899ce9f7e1e951fb54d33631be3523dd556a381e227da9e7a56b8051957cc5e3e59ee17d55d31856a1c324750ee7c9fb20ccceb95cfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
